apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: codemi-spring-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: codemi-spring-apps
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 85
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 600Mi
